Invoicio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include(('main.urls', 'main'), namespace='main')),
]

main/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('newClient/', views.createNewClient, name='newClient'),
    path('<int:client_id>/', views.clientDetail, name='clientDetail'),
    path('<int:client_id>/newInvoice/', views.newInvoice, name='newInvoice'),
]

main/models.py
from django.db import models
from django.db.models.base import Model
from django.db.models.fields import DateTimeField

# Create your models here.


class Client(models.Model):
    name = models.CharField(max_length=200)
    email = models.CharField(max_length=255, blank=True)
    phone = models.CharField(max_length=20, blank=True)


class Address(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    address = models.CharField(max_length=255)
    address2 = models.CharField(max_length=100, blank=True)
    city = models.CharField(max_length=255)
    state = models.CharField(max_length=2)
    zipcode = models.IntegerField()

# will I need to add a tax field?


class Invoice(models.Model):
    title = models.CharField(max_length=255)
    date = models.DateTimeField(auto_now=True)
    due_date = models.DateTimeField(auto_now=False)
    subtotal = models.DecimalField(max_digits=20, decimal_places=2)
    total = models.DecimalField(max_digits=20, decimal_places=2)
    amount_paid = models.DecimalField(max_digits=20, decimal_places=2)
    balance_due = models.DecimalField(max_digits=20, decimal_places=2)
    client = models.ForeignKey(
        Client, on_delete=models.CASCADE, null=True, blank=True)


class billedItem(models.Model):
    description = models.CharField(max_length=255)
    unit_price = models.DecimalField(max_digits=20, decimal_places=2)
    quantity = models.DecimalField(max_digits=20, decimal_places=2)
    total_price = models.DecimalField(max_digits=20, decimal_places=2)
    invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE)


class Note(models.Model):
    description = models.CharField(max_length=255)
    billed_item = models.ForeignKey(
        billedItem, on_delete=models.CASCADE, null=True, blank=True)

main/forms.py
from django import forms

class BilledItemForm(forms.Form):
  description = forms.CharField(label='Description', max_length=255)

class InvoiceForm(forms.Form):
  title = forms.CharField(label='Title', max_length=255)
  date = forms.DateField(label='Date')
  due_date = forms.DateField(label='Due Date')
  billedItem = BilledItemForm

main/views.py
from django.http.response import HttpResponse
from django.shortcuts import render
from .models import *
from .forms import *
# Create your views here.


def index(request):
    print(Client.objects.all())
    return render(request, 'main/index.html', {'clients': Client.objects.all()})


def createNewClient(request):
    print('here')
    if request.method == 'POST':
        print(request.POST.get('zip'))
        print(type(int(request.POST.get('zip'))))
        client = Client(name=request.POST.get('clientName'),
                        email=request.POST.get('clientEmail'))
        print(client)
        client.save()

        address = Address(client=client, address=request.POST.get('address'), address2=request.POST.get('address2'), city=request.POST.get(
            'city'), state=request.POST.get('state'), zipcode=request.POST.get('zip'))

        print(address)
        address.save()

    else:
        return render(request, 'main/newClient.html')


def clientDetail(request, client_id):
    print(Client.objects.get(pk=client_id))
    return render(request, 'main/clientDetail.html', {'client': Client.objects.get(pk=client_id)})


def newInvoice(request, client_id):
    if request.method == 'POST':
        client = Client.objects.get(pk=client_id)
        print(request.POST)
        # r = request.POST
        # invoice = Invoice(title=r.get('title'), date=, due_date=, subtotal=, total=, amount_paid=, balance_due=, client=client)
        # invoice.save()

    else:
        return render(request, 'main/newInvoice.html', {'form': InvoiceForm})

main/templates/main/clientDetail.html
<h1>{{client.name}}</h1>
<div>
  <p>{{client.email}}</p>
  <p>{{client.address}}</p>
</div>


<button onclick="location.href = '{% url 'main:newInvoice' client.id %}'">New Invoice</button>

{% for invoice in invoices %}
<li><a>{{invoice.number}}</a></li>
{% endfor %}

<button id='delete'>Delete Client</button>

main/templates/main/index.html
{% for client in clients %}
<button onclick="location.href = '{% url 'main:clientDetail' client.id %}'">{{client.name}}</button>
{% endfor %}

<button onclick="location.href ='newClient/'">Create New client</button>

main/templates/main/newClient.html
<form method='POST'>
  {% csrf_token %}
  <div id='clientInput'>
    <label>Name</label>
    <input type='text' class='textInput' name='clientName'>
    <label>Email</label>
    <input type='text' class='textInput' name='clientEmail'>
  </div>

  <div id='addressInput'>
    <label>Address</label>
    <input type='text' class='textInput' name='address'>

    <label>Address Line 2</label>
    <input type='text' class='textInput' name='address2'>

    <label>City</label>
    <input type='text' class='textInput' name='city'>

    <label>State</label>
    <input type='text' class='textInput' name='state'>

    <label>Zip Code</label>
    <input type='number' class='textInput' name='zip'>
  </div>

  <button type='submit'>Submit</button>
</form>

main/templates/main/newInvoice.html
<form action='/InvoiceForm/' method='post'>
  {% csrf_token %}
  {{ form }}
  <input type='submit' value='Submit'>
</form>

main/templates/main/newInvoiceOld.html
<!DOCTYPE html>

<body>
  <h1>Create New Invoice</h1>

  <form method='POST'>
    {% csrf_token %}
    <div id='title-container'>
      <label>Title</label>
      <input type='text' class='textInput' name='title'>
    </div>

    <div id='dates-container'>
      <label>Date</label>
      <input type='date' class='dateInput' name='date'>
      <label>Due Date</label>
      <input type='date' class='dateInput' name='due_date'>
    </div>

    <h3>Billed Items</h3>
    <div id='billed-items-container'>
      <template id='billed-item-template'>
        <div id='billed-item-0'>
          <label>Description</label>
          <input type='text' class='textInput' name='description'>
          <label>Unit Price</label>
          <input type='text' class='numberInput' name='unit_price'>
          <label>Quantity</label>
          <input type='text' class='numberInput' name='quantity'>
          <label>Total Price</label>
          <input type='text' type='numberInput' name='total_price'>
          <button id='add-note' onclick="addNote(this); return false;">Add a Note</button>
        </div>
      </template>
      <button id='add-billed-item' onclick="duplicate(this); return false;">Add a Billed
        Item</button>
    </div>



    <h3>Totals</h3>
    <div id='money-container'>
      <label>Subtotal</label>
      <input type='text' class='numberInput' name='subtotal'>
      <label>Total</label>
      <input type='text' class='numberInput' name='total'>
      <label>Amount Paid</label>
      <input type='text' class='numberInput' name='amount_paid'>
      <label>Balance Due</label>
      <input type='text' class='numberInput' name='balance_due'>
    </div>
    <button type='submit'>Submit</button>
  </form>


</body>

<script>
  var i = 0;
  function duplicate(elem) {

    var template = document.getElementById('billed-item-template');

    var clone = template.content.firstElementChild.cloneNode(true);

    clone.id = 'billed-item-' + ++i;

    inputs = clone.querySelectorAll('input');
    for (ind = 0; ind < inputs.length; ind++) {
      var name = inputs[ind].name;
      console.log(name);
      inputs[ind].name = name + i;
    }
    elem.parentNode.appendChild(clone);
  }

  function addNote(elem) {
    console.log(elem.parentElement)
    var elNumber = elem.parentNode.id.substr(elem.parentNode.id.length - 1);
    noteDiv = document.createElement('div');
    noteDiv.id = 'note-container-' + elNumber;

    noteInput = document.createElement('input');
    noteInput.type = 'text';
    noteInput.class = 'textInput';
    noteInput.name = 'note_description' + elNumber;

    noteDiv.appendChild(noteInput);

    elem.parentNode.appendChild(noteDiv);
  }
</script>